### ISSUE TITLE
Save map fails on malformed description

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#1992]
The backend cannot handle a description containing the character sequence &/

To reproduce:
- Create a new map
- Open the Save dialog
- Input &/ in the description
- Save

You will receive an error.
Here the response from the dev tools : 
```
JAXBException occurred : Unexpected character '/' (code 47) (expected a name start character)
 at [row,col {unknown-source}]: [1,25]. Unexpected character '/' (code 47) (expected a name start character)
 at [row,col {unknown-source}]: [1,25]. 
```
See coments below for details about all the UI use cases that fail.

**Comment by offtherailz** [comment]
This should be fixed by #2579, can you test it again?

**Comment by chiaracurcio** [comment]
the error is still present 
note that writing this text '&/' in the description you can't save the map with this text.
This is the error:

![immagine](https://user-images.githubusercontent.com/33256901/36432048-7bb5f502-1659-11e8-9fc6-c94555d03f67.png)

In the same way editing an existing map card when you are in home 'Edit Map Properties' you have an error saving the map card with this text description '&/': Network error

![immagine](https://user-images.githubusercontent.com/33256901/36432298-274818be-165a-11e8-8991-2b711a33f6d0.png)

both error are the same also when you write in the 'name' of the map this same text: &/

**Comment by offtherailz** [comment]
Ok,
confirm. I add the error from GeoStore for completeness:
```
JAXBException occurred : Unexpected character '/' (code 47) (expected a name start character)
 at [row,col {unknown-source}]: [1,25]. Unexpected character '/' (code 47) (expected a name start character)
 at [row,col {unknown-source}]: [1,25]. 
```

**Comment by kasongoyo** [comment]
@chiaracurcio I think the problem does not exist any longer. I have tried and the saving went through no matter what character I have placed in desc or name field? Can you confirm this behaviour?

**Comment by tdipisa** [comment]
@kasongoyo I'm no longer able to reproduce the issue, probably the issue has been solved. Please move the issue to Test column so Testers can retest it.
