### ISSUE TITLE
The print pdf is not generated

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#7963]
On QA the print pdf is not generated.

**How to Reproduce**
- Open a map
- Click on Options > Print
- Click on Print
- Click on Download 

*Expected Result*
The print pdf is downloaded

*Current Result*
The print pdf is not generated

**Comment by randomorder** [comment]
should be fixed @tdipisa

**Comment by tdipisa** [comment]
@randomorder the problem is still the same for me unfortunately on QA. Do you need to check it together?
